services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=dev
      - REDIS_URL=redis://redis:6379
      - MONGO_USERNAME=username
      - MONGO_PASSWORD=pass
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
    volumes:
      - .:/app
      - /app/node_modules
    x-develop:
      watch:
        - ./**/*.ts

  mongodb:
    image: 'mongo:4.4'
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    command: mongod --quiet

  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  postgres:
    image: 'postgres:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=mydatabase
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  redis-data:
  postgres-data:
