version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - NODE_ENV=dev
    volumes:
      - .:/app
      - /app/node_modules
 